### ISSUE TITLE
Roadmap 2.0.0

### ISSUE THREAD

**Issue by twiro** [twiro/multilingual#14]
### Roadmap for the upcoming 2.0.0-release

This list represents the current state of the `integration`-branch.

### Updates & Features:

- [x] Improve frontend language detection ([#12](https://github.com/twiro/multilingual/issues/12))
- [x] Add support for most common multilingual url-structures ([#12](https://github.com/twiro/multilingual/issues/12))
- [x] Add support for (sub)domain-language-mapping ([#12](https://github.com/twiro/multilingual/issues/12))
- [x] Add basic support for (optional) region-codes ([#13](https://github.com/twiro/multilingual/issues/13))
- [x] Make redirecting optional and add configuration-settings for different scenarios ([#10](https://github.com/twiro/multilingual/issues/10))
- [ ] PHP7 Support

### Documentation:

- [ ] Frontend language (and region) detection mechanism
- [ ] Url-structures & routing
- [ ] Redirecting
- [ ] Regions

### Testing:

All the newly supported language detection methods and url-structures need to be tested in different scenarios and in combination with other (routing-)extensions. **Any help and feedback is very welcome!**
